- hosts: all
  tasks:
    - name: Symlink pbox script
      file:
        src: '{{playbook_dir}}/pbox'
        dest: ~/.bin/pbox
        state: link
    - name: Symlink pbox-edit script
      file:
        src: '{{playbook_dir}}/pbox-edit'
        dest: ~/.bin/pbox-edit
        state: link
  roles:
    - base
    - shell
    - tmux
    - xorg
    - xmonad
    - nodejs
    - docker
    - java8
    - idea
    - clj
    - fpp
    - ruby
    - python
    - gcloud
    - cpp
    - dwb
    - chromium
    - git
    - psql
    - urxvt
    - vim
    - maven
