- hosts: all
  roles:
    - base
    - shell
    - tmux
    - xorg
    - xmonad
    - nodejs
    - docker
    - java8
    - idea
    - clj
    - fpp
    - ruby
    - python
    - gcloud
    - cpp
    - dwb
    - chromium
    - git
    - psql
    - urxvt
    - vim
    - maven
