- hosts: all
  tasks:
    - name: Symlink pbox scripts
      file:
        src: '{{playbook_dir}}/bin/{{item}}'
        dest: ~/.bin/{{item}}
        state: link
      with_items:
        - pbox-apply
        - pbox-edit
      tags: [pbox]
  roles:
    - base
    - bash
    - python
    - haskell
    - nodejs
    - ruby
    - clojure
    - cpp
    - java
    - xorg
    - rxvt
    - xmonad
    - vim
    - tmux
    - git
    - docker
    - dwb
    - chromium
    - idea
    - fpp
    - gcloud
    - psql
    - jq
    - scripts
