- hosts: all
  tasks:
    - name: Symlink pbox scripts
      file:
        src: '{{playbook_dir}}/bin/{{item}}'
        dest: ~/.bin/{{item}}
        state: link
      with_items:
        - pbox-apply
        - pbox-edit
        - pbox-cd
      tags: [pbox]
  roles:
    - base
    - shell
    - tmux
    - xorg
    - xmonad
    - nodejs
    - docker
    - java8
    - idea
    - clj
    - fpp
    - ruby
    - python
    - gcloud
    - cpp
    - dwb
    - chromium
    - git
    - psql
    - urxvt
    - vim
    - maven
