- name: Install packages
  become: yes
  become_user: root
  apt:
    name: '{{item}}'
    state: latest
  with_items:
    - xorg
    - xcompmgr
    - hsetroot
    - ttf-liberation
  tags: [xorg]

- name: Create folder ~/.xkb/symbols
  file:
    path: ~/.xkb/symbols
    state: directory
  tags: [xorg]

- name: Install keyboard layout ~/.xkb/symbols/poskeys
  copy:
    src: poskeys
    dest: ~/.xkb/symbols/poskeys
  tags: [xorg]

- name: Install script ~/.bin/setxkb
  copy:
    src: setxkb
    dest: ~/.bin/setxkb
    mode: 0755
  tags: [xorg]

- name: Install dotfile ~/.xinitrc
  copy:
    src: xinitrc
    dest: ~/.xinitrc
  tags: [xorg]

- name: Install dotfile ~/.Xresources
  copy:
    src: Xresources
    dest: ~/.Xresources
  tags: [xorg]

- name: Create folder ~/.Xresources.d
  file:
    path: ~/.Xresources.d
    state: directory
  tags: [xorg]

- name: Render template ~/.Xresources.d/colorscheme
  template:
    src: colorscheme.j2
    dest: ~/.Xresources.d/colorscheme
  tags: [xorg]
