- name: Install curated /etc/hosts from github.com/StevenBlack
  become: yes
  become_user: root
  get_url:
    url: https://raw.githubusercontent.com/StevenBlack/hosts/f7937639f14b062aff75c5c366f9d5b6a6eb1916/hosts
    dest: /etc/hosts
  tags: [hosts]

- name: Add hostname to /etc/hosts
  become: yes
  become_user: root
  lineinfile:
    dest: /etc/hosts
    line: '127.0.0.1 {{host}}.localdomain {{host}}'
  tags: [hosts]
