- name: Add nodesource apt key
  become: yes
  become_user: root
  shell: curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
  tags: [nodejs]

- name: Add repository deb.nodesource.com/node_7.x
  become: yes
  become_user: root
  apt_repository:
    repo: deb https://deb.nodesource.com/node_7.x trusty main
    state: present
    update_cache: yes
  tags: [nodejs]

- name: Install nodejs packages
  become: yes
  become_user: root
  apt:
    name: '{{item}}'
    state: latest
  with_items:
    - nodejs
  tags: [nodejs]

- name: Install npm packages
  become: yes
  become_user: root
  npm:
    name: '{{item}}'
    global: yes
  with_items:
    - npm
    - yarn
  tags: [nodejs]
