- name: Add repository zeal-developers/ppa
  become: yes
  become_user: root
  apt_repository:
    repo: ppa:zeal-developers/ppa
    update_cache: yes
  tags: [zeal]

- name: Install package
  become: yes
  become_user: root
  apt:
    name: zeal
    state: latest
  tags: [zeal]

- name: Create folder ~/.local/share/Zeal/Zeal/docsets
  file:
    path: ~/.local/share/Zeal/Zeal/docsets
    state: directory
  tags: [zeal]

- name: Download x86 docset
  get_url:
    url: http://newyork.kapeli.com/feeds/zzz/user_contributed/build/IntelASMx86/IntelASMx86.tgz
    dest: ~/.local/share/Zeal/Zeal/docsets/IntelASMx86.tgz
  tags: [zeal]

- name: Unarchive x86 docset
  unarchive:
    copy: no
    src: ~/.local/share/Zeal/Zeal/docsets/IntelASMx86.tgz
    dest: ~/.local/share/Zeal/Zeal/docsets
    creates: ~/.local/share/Zeal/Zeal/docsets/IntelASMx86.docset
  tags: [zeal]
