- name: Install Python packages
  become: yes
  become_user: root
  apt:
    name: '{{item}}'
    state: latest
  with_items:
    - python-pip
    - python-dev
    - python3-dev
    - python3-pip
    - python-virtualenv
    - pkg-config
    - libfreetype6-dev
  tags: [python]

- name: Install pip packages
  become: yes
  become_user: root
  pip:
    name: '{{item}}'
    state: latest
    executable: /usr/bin/pip2
  with_items:
    - pip
    - docopt
    - cqlsh==4.1.1 # 2.x only
    - fabric # 2.x only
    - requests[security] # or else SSL warnings
  tags: [python]

- name: Install pip3 packages
  become: yes
  become_user: root
  pip:
    name: '{{item}}'
    state: latest
    executable: /usr/bin/pip3
  with_items:
    - jupyter
    - pandas
    - matplotlib
    - proselint
    - pylint
    - pycodestyle
    - docopt
    - requests[security] # or else SSL warnings
    - requests_crtauth
  tags: [python]
