- name: Create folder ~/software/fpp
  file:
    path: ~/software/fpp
    state: directory
  tags: [fpp, folders]

- name: Download fpp.0.6.2.tar.gz
  get_url:
    url: https://github.com/facebook/PathPicker/releases/download/0.6.2/fpp.0.6.2.tar.gz
    dest: ~/software/fpp/fpp.0.6.2.tar.gz
  tags: [fpp]

- name: Create folder ~/software/fpp/fpp-0.6.2
  file:
    path: ~/software/fpp/fpp-0.6.2
    state: directory
  tags: [fpp, folders]

- name: Unarchive fpp.0.6.2.tar.gz
  unarchive:
    copy: no
    src: ~/software/fpp/fpp.0.6.2.tar.gz
    dest: ~/software/fpp/fpp-0.6.2
    creates: ~/software/fpp/fpp-0.6.2/fpp
  tags: [fpp]

- name: Symlink ~/.bin/fpp
  file:
    src: ~/software/fpp/fpp-0.6.2/fpp
    dest: ~/.bin/fpp
    state: link
  tags: [fpp]
