- name: Add repository git-core/ppa
  become: yes
  become_user: root
  apt_repository:
    repo: ppa:git-core/ppa
    update_cache: yes
  tags: [git]

- name: Install package
  become: yes
  become_user: root
  apt:
    name: git
    state: latest
  tags: [git]

- name: Install dotfile ~/.gitconfig
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig
  tags: [git]

- name: Install NPM package diff-so-fancy
  become: yes
  become_user: root
  npm:
    name: diff-so-fancy
    global: yes
  tags: [git]
