- name: Add PPA repository keithw/mosh
  become: yes
  become_user: root
  apt_repository:
    repo: ppa:keithw/mosh
    update_cache: yes
  tags: [mosh]

- name: Install package mosh
  become: yes
  become_user: root
  apt:
    name: mosh
  tags: [mosh]
