- name: Create folder ~/software/google-cloud-sdk
  file:
    path: ~/software/google-cloud-sdk
    state: directory
  tags: [gcloud]

- name: Download google-cloud-sdk.tar.gz
  get_url:
    url: https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.tar.gz
    dest: ~/software/google-cloud-sdk/google-cloud-sdk.tar.gz
  tags: [gcloud]

- name: Unpack google-cloud-sdk.tar.gz
  unarchive:
    copy: no
    src: ~/software/google-cloud-sdk/google-cloud-sdk.tar.gz
    dest: ~/software/google-cloud-sdk
    creates: ~/software/google-cloud-sdk/google-cloud-sdk
  tags: [gcloud]

- name: Install Google Cloud SDK
  shell: $SHELL -lc 'CLOUDSDK_CORE_DISABLE_PROMPTS=1 ~/software/google-cloud-sdk/google-cloud-sdk/install.sh --command-completion False --path-update False'
  args:
    creates: ~/software/google-cloud-sdk/google-cloud-sdk/properties
  tags: [gcloud]
