- name: Add PPA pi-rho/dev
  become: yes
  become_user: root
  apt_repository:
    repo: 'ppa:pi-rho/dev'
    update_cache: yes
  tags: [tmux, repositories]

- name: Install package tmux=2.0-1~ppa1~t
  become: yes
  become_user: root
  apt:
    name: tmux=2.0-1~ppa1~t
    state: present
  tags: [tmux, packages]

- name: Install ~/.tmux.conf
  copy:
    src: tmux.conf
    dest: ~/.tmux.conf
  tags: [tmux, dotfiles]

- name: Install script tmuxssh
  copy:
    src: tmuxssh
    dest: ~/.bin/tmuxssh
    mode: 0755
  tags: [tmux, bin]

- name: Install script tmuxargs
  copy:
    src: tmuxargs
    dest: ~/.bin/tmuxargs
    mode: 0755
  tags: [tmux, bin]

- name: Install script stmux
  copy:
    src: stmux
    dest: ~/.bin/stmux
    mode: 0755
  tags: [tmux, bin]

- name: Install script print-tmux-colors
  copy:
    src: print-tmux-colors
    dest: ~/.bin/print-tmux-colors
    mode: 0755
  tags: [tmux, bin]
