- name: Install package
  become: yes
  become_user: root
  apt:
    name: dwb
    state: latest
  tags: [dwb]

- name: Create folder ~/.config/dwb
  file:
    path: ~/.config/dwb
    state: directory
  tags: [dwb]

- name: Render template ~/.config/dwb/settings
  template:
    src: settings.j2
    dest: ~/.config/dwb/settings
  tags: [dwb]

- name: Install dotfile ~/.config/dwb/keys
  copy:
    src: keys
    dest: ~/.config/dwb/keys
  tags: [dwb]

- name: Add search engines
  lineinfile:
    dest: ~/.config/dwb/searchengines
    line: '{{item}}'
    create: yes
  with_items:
    - g https://www.google.com/search?q=_dwb_search_submit_
    - dd https://duckduckgo.com/?q=_dwb_search_submit_
    - gh https://github.com/search?utf8=%E2%9C%93&q=_dwb_search_submit_
    - gho https://github.com/odsod/_dwb_search_submit_
    - mdn https://developer.mozilla.org/en-US/search?q=_dwb_search_submit_
    - mvn https://mvnrepository.com/search?q=_dwb_search_submit_
  tags: [dwb]
