- name: Add poscar to sudoers
  become: yes
  become_user: root
  lineinfile:
    dest: /etc/sudoers.d/poscar
    line: poscar ALL=(ALL) NOPASSWD:ALL
    state: present
    create: yes
    validate: visudo -cf %s
  tags: [base]

- name: Create folder ~/.bin
  file:
    path: ~/.bin
    state: directory
  tags: [base]

- name: Install packages required for adding APT repositories
  become: yes
  become_user: root
  apt:
    name: '{{item}}'
    state: latest
  with_items:
    - python-apt
    - apt-transport-https
    - python-software-properties
    - software-properties-common
  tags: [base]

- name: Add APT repository trusty-backports
  become: yes
  become_user: root
  apt_repository:
    repo: 'deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse'
    state: present
    update_cache: yes
  tags: [base]

- name: Install base packages
  become: yes
  become_user: root
  apt:
    name: '{{item}}'
  with_items:
    - sudo
    - htop
    - unzip
    - curl
    - parallel
    - pssh
    - gdb
    - ncdu
  tags: [base]
