- name: Install XMonad packages
  become: yes
  become_user: root
  apt:
    name: '{{item}}'
    state: latest
  with_items:
    - cabal-install
    - unclutter
    - suckless-tools
  tags: [xmonad]

- name: Install XMonad cabal packages
  shell: cabal install xmonad xmonad-contrib
  args:
    creates: ~/.cabal/bin/xmonad
  tags: [xmonad]

- name: Create folder ~/.xmonad
  file:
    path: ~/.xmonad
    state: directory
  tags: [xmonad]

- name: Install dotfile ~/.xmonad/xmonad.hs
  copy:
    src: xmonad.hs
    dest: ~/.xmonad/xmonad.hs
  tags: [xmonad]

- name: Install mydmenu script
  copy:
    src: mydmenu
    dest: ~/.bin/mydmenu
    mode: 0755
  tags: [xmonad]
