- name: Install XMonad packages
  become: yes
  become_user: root
  apt:
    name: '{{item}}'
    state: latest
  with_items:
    - cabal-install
    - unclutter
    - suckless-tools
    # cabal build dependencies
    - libx11-dev
    - libxinerama-dev
    - libxext-dev
    - libxrandr-dev
  tags: [xmonad]

- name: Install XMonad cabal packages
  shell: cabal update && cabal install xmonad xmonad-contrib
  args:
    creates: ~/.cabal/bin/xmonad
  tags: [xmonad]

- name: Create folder ~/.xmonad
  file:
    path: ~/.xmonad
    state: directory
  tags: [xmonad]

- name: Install dotfile ~/.xmonad/xmonad.hs
  copy:
    src: xmonad.hs
    dest: ~/.xmonad/xmonad.hs
  tags: [xmonad]

- name: Install script ~/.bin/mydmenu
  copy:
    src: mydmenu
    dest: ~/.bin/mydmenu
    mode: 0755
  tags: [xmonad]

- name: Install script ~/.bin/pmenu
  copy:
    src: pmenu
    dest: ~/.bin/pmenu
    mode: 0755
  tags: [xmonad]
