- name: Create folder ~/software/rubies
  file:
    path: ~/software/rubies
    state: directory
  tags: [ruby]

- name: Download ruby-2.2.1.tar.bz2
  get_url:
    url: https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/14.04/x86_64/ruby-2.2.1.tar.bz2
    dest: ~/software/rubies/ruby-2.2.1.tar.bz2
  tags: [ruby]

- name: Unarchive ruby-2.2.1.tar.bz2
  unarchive:
    copy: no
    src: ~/software/rubies/ruby-2.2.1.tar.bz2
    dest: ~/software/rubies
    creates: ~/software/rubies/ruby-2.2.1
  tags: [ruby]

- name: Create folder ~/software/chruby
  file:
    path: ~/software/chruby
    state: directory
  tags: [ruby]

- name: Download chruby-0.3.9.tar.gz
  get_url:
    url: https://github.com/postmodern/chruby/archive/v0.3.9.tar.gz
    dest: ~/software/chruby/chruby-0.3.9.tar.gz
  tags: [ruby]

- name: Unarchive chruby-0.3.9.tar.gz
  unarchive:
    copy: no
    src: ~/software/chruby/chruby-0.3.9.tar.gz
    dest: ~/software/chruby
    creates: ~/software/chruby/chruby-0.3.9
  tags: [ruby]

- name: Install dotfile ~/.gemrc
  copy:
    src: gemrc
    dest: ~/.gemrc
  tags: [ruby]

- name: Install gems
  gem:
    name: rake
    executable: ~/software/rubies/ruby-2.2.1/bin/gem
  with_items:
    - puppet-lint
    - mdl
    - ruby-puppetdb
  tags: [ruby]
