- name: Add PPA repository brightbox/ruby-ng
  become: yes
  become_user: root
  apt_repository:
    repo: ppa:brightbox/ruby-ng
    update_cache: yes
  tags: [ruby]

- name: Install Ruby 2.3
  become: yes
  become_user: root
  apt:
    name: ruby2.3
    state: latest
  tags: [ruby]

- name: Install dotfile ~/.gemrc
  copy:
    src: gemrc
    dest: ~/.gemrc
  tags: [ruby]

- name: Install gems
  become: yes
  become_user: root
  gem:
    name: '{{item}}'
    user_install: no
  with_items:
    - puppet-lint
    - mdl
    - ruby-puppetdb
  tags: [ruby]
