- name: Clone GitHub repo sstephenson/rbenv to ~/.rbenv
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: ~/.rbenv
    update: no
    accept_hostkey: yes
  tags: [ruby, rbenv]

- name: Clone GitHub repo sstephenson/ruby-build to ~/.rbenv/plugins
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build
    update: no
    accept_hostkey: yes
  tags: [ruby, rbenv]

- name: Install 2.2.2
  shell: $SHELL -lc 'eval "$(rbenv init -)" && rbenv install 2.2.2'
  args:
    creates: ~/.rbenv/versions/2.2.2
  tags: [ruby, rbenv]

- name: Set 2.2.2 as default
  lineinfile:
    line: 2.2.2
    dest: ~/.rbenv/version
    create: yes
  tags: [ruby, rbenv]

- name: Install dotfile ~/.gemrc
  copy:
    src: gemrc
    dest: ~/.gemrc
  tags: [ruby, gems]

- name: Install gem ruby-puppetdb
  shell: $SHELL -lc 'eval "$(rbenv init -)" && gem install puppet ruby-puppetdb'
  args:
    creates: ~/.rbenv/versions/2.2.2/bin/find-nodes
  tags: [ruby, gems]

- name: Install gem puppet-lint
  shell: $SHELL -lc 'eval "$(rbenv init -)" && gem install puppet-lint'
  args:
    creates: ~/.rbenv/versions/2.2.2/bin/puppet-lint
  tags: [ruby, gems]

- name: Install gem mdl
  shell: $SHELL -lc 'eval "$(rbenv init -)" && gem install mdl'
  args:
    creates: ~/.rbenv/versions/2.2.2/bin/mdl
  tags: [ruby, gems]
